package value_object

import (
	"github.com/hzmat24/api/domain/exception"
	"strings"
)

var (
	ErrInvalidCountryCode = exception.New("invalid country code")
)

type CountryCode string

// ParseCountryCode validates and returns a new CountryCode object
func ParseCountryCode(value string) (CountryCode, error) {
	if !isValidCountryCode(value) {
		return "", ErrInvalidCountryCode
	}
	return CountryCode(strings.TrimSpace(value)), nil
}

// isValidCountryCode performs country code validation
func isValidCountryCode(countryCode string) bool {
	for _, country := range Countries {
		if countryCode == country.Code2 || countryCode == country.Code3 {
			return true
		}
	}
	return false
}

// GetValue returns the underlying string representation of the CountryCode
func (e CountryCode) String() string {
	return string(e)
}

// Country struct definition
type Country struct {
	Code2 string
	Code3 string
	Name  string
}

// Countries slice definition
var Countries = []Country{
	{Code2: "AF", Code3: "AFG", Name: "Afghanistan"},
	{Code2: "AX", Code3: "ALA", Name: "Åland Islands"},
	{Code2: "AL", Code3: "ALB", Name: "Albania"},
	{Code2: "DZ", Code3: "DZA", Name: "Algeria"},
	{Code2: "AS", Code3: "ASM", Name: "American Samoa"},
	{Code2: "AD", Code3: "AND", Name: "Andorra"},
	{Code2: "AO", Code3: "AGO", Name: "Angola"},
	{Code2: "AI", Code3: "AIA", Name: "Anguilla"},
	{Code2: "AQ", Code3: "ATA", Name: "Antarctica"},
	{Code2: "AG", Code3: "ATG", Name: "Antigua and Barbuda"},
	{Code2: "AR", Code3: "ARG", Name: "Argentina"},
	{Code2: "AM", Code3: "ARM", Name: "Armenia"},
	{Code2: "AW", Code3: "ABW", Name: "Aruba"},
	{Code2: "AU", Code3: "AUS", Name: "Australia"},
	{Code2: "AT", Code3: "AUT", Name: "Austria"},
	{Code2: "AZ", Code3: "AZE", Name: "Azerbaijan"},
	{Code2: "BS", Code3: "BHS", Name: "Bahamas"},
	{Code2: "BH", Code3: "BHR", Name: "Bahrain"},
	{Code2: "BD", Code3: "BGD", Name: "Bangladesh"},
	{Code2: "BB", Code3: "BRB", Name: "Barbados"},
	{Code2: "BY", Code3: "BLR", Name: "Belarus"},
	{Code2: "BE", Code3: "BEL", Name: "Belgium"},
	{Code2: "BZ", Code3: "BLZ", Name: "Belize"},
	{Code2: "BJ", Code3: "BEN", Name: "Benin"},
	{Code2: "BM", Code3: "BMU", Name: "Bermuda"},
	{Code2: "BT", Code3: "BTN", Name: "Bhutan"},
	{Code2: "BO", Code3: "BOL", Name: "Bolivia (Plurinational State of)"},
	{Code2: "BQ", Code3: "BES", Name: "Bonaire Sint Eustatius Saba"},
	{Code2: "BA", Code3: "BIH", Name: "Bosnia and Herzegovina"},
	{Code2: "BW", Code3: "BWA", Name: "Botswana"},
	{Code2: "BV", Code3: "BVT", Name: "Bouvet Island"},
	{Code2: "BR", Code3: "BRA", Name: "Brazil"},
	{Code2: "IO", Code3: "IOT", Name: "British Indian Ocean Territory"},
	{Code2: "BN", Code3: "BRN", Name: "Brunei Darussalam"},
	{Code2: "BG", Code3: "BGR", Name: "Bulgaria"},
	{Code2: "BF", Code3: "BFA", Name: "Burkina Faso"},
	{Code2: "BI", Code3: "BDI", Name: "Burundi"},
	{Code2: "CV", Code3: "CPV", Name: "Cabo Verde"},
	{Code2: "KH", Code3: "KHM", Name: "Cambodia"},
	{Code2: "CM", Code3: "CMR", Name: "Cameroon"},
	{Code2: "CA", Code3: "CAN", Name: "Canada"},
	{Code2: "KY", Code3: "CYM", Name: "Cayman Islands"},
	{Code2: "CF", Code3: "CAF", Name: "Central African Republic"},
	{Code2: "TD", Code3: "TCD", Name: "Chad"},
	{Code2: "CL", Code3: "CHL", Name: "Chile"},
	{Code2: "CN", Code3: "CHN", Name: "China"},
	{Code2: "CX", Code3: "CXR", Name: "Christmas Island"},
	{Code2: "CC", Code3: "CCK", Name: "Cocos (Keeling) Islands"},
	{Code2: "CO", Code3: "COL", Name: "Colombia"},
	{Code2: "KM", Code3: "COM", Name: "Comoros"},
	{Code2: "CD", Code3: "COD", Name: "Congo (the Democratic Republic of the)"},
	{Code2: "CG", Code3: "COG", Name: "Congo"},
	{Code2: "CK", Code3: "COK", Name: "Cook Islands"},
	{Code2: "CR", Code3: "CRI", Name: "Costa Rica"},
	{Code2: "CI", Code3: "CIV", Name: "Côte d'Ivoire"},
	{Code2: "HR", Code3: "HRV", Name: "Croatia"},
	{Code2: "CU", Code3: "CUB", Name: "Cuba"},
	{Code2: "CW", Code3: "CUW", Name: "Curaçao"},
	{Code2: "CY", Code3: "CYP", Name: "Cyprus"},
	{Code2: "CZ", Code3: "CZE", Name: "Czechia"},
	{Code2: "DK", Code3: "DNK", Name: "Denmark"},
	{Code2: "DJ", Code3: "DJI", Name: "Djibouti"},
	{Code2: "DM", Code3: "DMA", Name: "Dominica"},
	{Code2: "DO", Code3: "DOM", Name: "Dominican Republic"},
	{Code2: "EC", Code3: "ECU", Name: "Ecuador"},
	{Code2: "EG", Code3: "EGY", Name: "Egypt"},
	{Code2: "SV", Code3: "SLV", Name: "El Salvador"},
	{Code2: "GQ", Code3: "GNQ", Name: "Equatorial Guinea"},
	{Code2: "ER", Code3: "ERI", Name: "Eritrea"},
	{Code2: "EE", Code3: "EST", Name: "Estonia"},
	{Code2: "SZ", Code3: "SWZ", Name: "Eswatini"},
	{Code2: "ET", Code3: "ETH", Name: "Ethiopia"},
	{Code2: "FK", Code3: "FLK", Name: "Falkland Islands"},
	{Code2: "FO", Code3: "FRO", Name: "Faroe Islands"},
	{Code2: "FJ", Code3: "FJI", Name: "Fiji"},
	{Code2: "FI", Code3: "FIN", Name: "Finland"},
	{Code2: "FR", Code3: "FRA", Name: "France"},
	{Code2: "GF", Code3: "GUF", Name: "French Guiana"},
	{Code2: "PF", Code3: "PYF", Name: "French Polynesia"},
	{Code2: "TF", Code3: "ATF", Name: "French Southern Territories"},
	{Code2: "GA", Code3: "GAB", Name: "Gabon"},
	{Code2: "GM", Code3: "GMB", Name: "Gambia"},
	{Code2: "GE", Code3: "GEO", Name: "Georgia"},
	{Code2: "DE", Code3: "DEU", Name: "Germany"},
	{Code2: "GH", Code3: "GHA", Name: "Ghana"},
	{Code2: "GI", Code3: "GIB", Name: "Gibraltar"},
	{Code2: "GR", Code3: "GRC", Name: "Greece"},
	{Code2: "GL", Code3: "GRL", Name: "Greenland"},
	{Code2: "GD", Code3: "GRD", Name: "Grenada"},
	{Code2: "GP", Code3: "GLP", Name: "Guadeloupe"},
	{Code2: "GU", Code3: "GUM", Name: "Guam"},
	{Code2: "GT", Code3: "GTM", Name: "Guatemala"},
	{Code2: "GG", Code3: "GGY", Name: "Guernsey"},
	{Code2: "GN", Code3: "GIN", Name: "Guinea"},
	{Code2: "GW", Code3: "GNB", Name: "Guinea-Bissau"},
	{Code2: "GY", Code3: "GUY", Name: "Guyana"},
	{Code2: "HT", Code3: "HTI", Name: "Haiti"},
	{Code2: "HM", Code3: "HMD", Name: "Heard Island and McDonald Islands"},
	{Code2: "VA", Code3: "VAT", Name: "Holy See [o]"},
	{Code2: "HN", Code3: "HND", Name: "Honduras"},
	{Code2: "HK", Code3: "HKG", Name: "Hong Kong"},
	{Code2: "HU", Code3: "HUN", Name: "Hungary"},
	{Code2: "IS", Code3: "ISL", Name: "Iceland"},
	{Code2: "IN", Code3: "IND", Name: "India"},
	{Code2: "ID", Code3: "IDN", Name: "Indonesia"},
	{Code2: "IR", Code3: "IRN", Name: "Iran (Islamic Republic of)"},
	{Code2: "IQ", Code3: "IRQ", Name: "Iraq"},
	{Code2: "IE", Code3: "IRL", Name: "Ireland"},
	{Code2: "IM", Code3: "IMN", Name: "Isle of Man"},
	{Code2: "IL", Code3: "ISR", Name: "Israel"},
	{Code2: "IT", Code3: "ITA", Name: "Italy"},
	{Code2: "JM", Code3: "JAM", Name: "Jamaica"},
	{Code2: "JP", Code3: "JPN", Name: "Japan"},
	{Code2: "JE", Code3: "JEY", Name: "Jersey"},
	{Code2: "JO", Code3: "JOR", Name: "Jordan"},
	{Code2: "KZ", Code3: "KAZ", Name: "Kazakhstan"},
	{Code2: "KE", Code3: "KEN", Name: "Kenya"},
	{Code2: "KI", Code3: "KIR", Name: "Kiribati"},
	{Code2: "KP", Code3: "PRK", Name: "Korea (the Democratic People's Republic of)"},
	{Code2: "KR", Code3: "KOR", Name: "Korea (the Republic of)"},
	{Code2: "KW", Code3: "KWT", Name: "Kuwait"},
	{Code2: "KG", Code3: "KGZ", Name: "Kyrgyzstan"},
	{Code2: "LA", Code3: "LAO", Name: "Lao People's Democratic Republic"},
	{Code2: "LV", Code3: "LVA", Name: "Latvia"},
	{Code2: "LB", Code3: "LBN", Name: "Lebanon"},
	{Code2: "LS", Code3: "LSO", Name: "Lesotho"},
	{Code2: "LR", Code3: "LBR", Name: "Liberia"},
	{Code2: "LY", Code3: "LBY", Name: "Libya"},
	{Code2: "LI", Code3: "LIE", Name: "Liechtenstein"},
	{Code2: "LT", Code3: "LTU", Name: "Lithuania"},
	{Code2: "LU", Code3: "LUX", Name: "Luxembourg"},
	{Code2: "MO", Code3: "MAC", Name: "Macao [s]"},
	{Code2: "MG", Code3: "MDG", Name: "Madagascar"},
	{Code2: "MW", Code3: "MWI", Name: "Malawi"},
	{Code2: "MY", Code3: "MYS", Name: "Malaysia"},
	{Code2: "MV", Code3: "MDV", Name: "Maldives"},
	{Code2: "ML", Code3: "MLI", Name: "Mali"},
	{Code2: "MT", Code3: "MLT", Name: "Malta"},
	{Code2: "MH", Code3: "MHL", Name: "Marshall Islands"},
	{Code2: "MQ", Code3: "MTQ", Name: "Martinique"},
	{Code2: "MR", Code3: "MRT", Name: "Mauritania"},
	{Code2: "MU", Code3: "MUS", Name: "Mauritius"},
	{Code2: "YT", Code3: "MYT", Name: "Mayotte"},
	{Code2: "MX", Code3: "MEX", Name: "Mexico"},
	{Code2: "FM", Code3: "FSM", Name: "Micronesia (Federated States of)"},
	{Code2: "MD", Code3: "MDA", Name: "Moldova (the Republic of)"},
	{Code2: "MC", Code3: "MCO", Name: "Monaco"},
	{Code2: "MN", Code3: "MNG", Name: "Mongolia"},
	{Code2: "ME", Code3: "MNE", Name: "Montenegro"},
	{Code2: "MS", Code3: "MSR", Name: "Montserrat"},
	{Code2: "MA", Code3: "MAR", Name: "Morocco"},
	{Code2: "MZ", Code3: "MOZ", Name: "Mozambique"},
	{Code2: "MM", Code3: "MMR", Name: "Myanmar [t]"},
	{Code2: "NA", Code3: "NAM", Name: "Namibia"},
	{Code2: "NR", Code3: "NRU", Name: "Nauru"},
	{Code2: "NP", Code3: "NPL", Name: "Nepal"},
	{Code2: "NL", Code3: "NLD", Name: "Netherlands, Kingdom of the"},
	{Code2: "NC", Code3: "NCL", Name: "New Caledonia"},
	{Code2: "NZ", Code3: "NZL", Name: "New Zealand"},
	{Code2: "NI", Code3: "NIC", Name: "Nicaragua"},
	{Code2: "NE", Code3: "NER", Name: "Niger"},
	{Code2: "NG", Code3: "NGA", Name: "Nigeria"},
	{Code2: "NU", Code3: "NIU", Name: "Niue"},
	{Code2: "NF", Code3: "NFK", Name: "Norfolk Island"},
	{Code2: "MK", Code3: "MKD", Name: "North Macedonia"},
	{Code2: "MP", Code3: "MNP", Name: "Northern Mariana Islands"},
	{Code2: "NO", Code3: "NOR", Name: "Norway"},
	{Code2: "OM", Code3: "OMN", Name: "Oman"},
	{Code2: "PK", Code3: "PAK", Name: "Pakistan"},
	{Code2: "PW", Code3: "PLW", Name: "Palau"},
	{Code2: "PS", Code3: "PSE", Name: "Palestine, State of"},
	{Code2: "PA", Code3: "PAN", Name: "Panama"},
	{Code2: "PG", Code3: "PNG", Name: "Papua New Guinea"},
	{Code2: "PY", Code3: "PRY", Name: "Paraguay"},
	{Code2: "PE", Code3: "PER", Name: "Peru"},
	{Code2: "PH", Code3: "PHL", Name: "Philippines"},
	{Code2: "PN", Code3: "PCN", Name: "Pitcairn [v]"},
	{Code2: "PL", Code3: "POL", Name: "Poland"},
	{Code2: "PT", Code3: "PRT", Name: "Portugal"},
	{Code2: "PR", Code3: "PRI", Name: "Puerto Rico"},
	{Code2: "QA", Code3: "QAT", Name: "Qatar"},
	{Code2: "RE", Code3: "REU", Name: "Réunion"},
	{Code2: "RO", Code3: "ROU", Name: "Romania"},
	{Code2: "RU", Code3: "RUS", Name: "Russian Federation"},
	{Code2: "RW", Code3: "RWA", Name: "Rwanda"},
	{Code2: "BL", Code3: "BLM", Name: "Saint Barthélemy"},
	{Code2: "SH", Code3: "SHN", Name: "Saint Helena Ascension Island Tristan da Cunha"},
	{Code2: "KN", Code3: "KNA", Name: "Saint Kitts and Nevis"},
	{Code2: "LC", Code3: "LCA", Name: "Saint Lucia"},
	{Code2: "MF", Code3: "MAF", Name: "Saint Martin (French part)"},
	{Code2: "PM", Code3: "SPM", Name: "Saint Pierre and Miquelon"},
	{Code2: "VC", Code3: "VCT", Name: "Saint Vincent and the Grenadines"},
	{Code2: "WS", Code3: "WSM", Name: "Samoa"},
	{Code2: "SM", Code3: "SMR", Name: "San Marino"},
	{Code2: "ST", Code3: "STP", Name: "Sao Tome and Principe"},
	{Code2: "SA", Code3: "SAU", Name: "Saudi Arabia"},
	{Code2: "SN", Code3: "SEN", Name: "Senegal"},
	{Code2: "RS", Code3: "SRB", Name: "Serbia"},
	{Code2: "SC", Code3: "SYC", Name: "Seychelles"},
	{Code2: "SL", Code3: "SLE", Name: "Sierra Leone"},
	{Code2: "SG", Code3: "SGP", Name: "Singapore"},
	{Code2: "SX", Code3: "SXM", Name: "Sint Maarten"},
	{Code2: "SK", Code3: "SVK", Name: "Slovakia"},
	{Code2: "SI", Code3: "SVN", Name: "Slovenia"},
	{Code2: "SB", Code3: "SLB", Name: "Solomon Islands"},
	{Code2: "SO", Code3: "SOM", Name: "Somalia"},
	{Code2: "ZA", Code3: "ZAF", Name: "South Africa"},
	{Code2: "GS", Code3: "SGS", Name: "South Georgia and the South Sandwich Islands"},
	{Code2: "SS", Code3: "SSD", Name: "South Sudan"},
	{Code2: "ES", Code3: "ESP", Name: "Spain"},
	{Code2: "LK", Code3: "LKA", Name: "Sri Lanka"},
	{Code2: "SD", Code3: "SDN", Name: "Sudan"},
	{Code2: "SR", Code3: "SUR", Name: "Suriname"},
	{Code2: "SJ", Code3: "SJM", Name: "Svalbard Jan Mayen"},
	{Code2: "CH", Code3: "CHE", Name: "Switzerland"},
	{Code2: "SE", Code3: "SWE", Name: "Sweden"},
	{Code2: "SY", Code3: "SYR", Name: "Syrian Arab Republic"},
	{Code2: "TW", Code3: "TWN", Name: "Taiwan (Province of China)"},
	{Code2: "TJ", Code3: "TJK", Name: "Tajikistan"},
	{Code2: "TZ", Code3: "TZA", Name: "Tanzania, the United Republic of"},
	{Code2: "TH", Code3: "THA", Name: "Thailand"},
	{Code2: "TL", Code3: "TLS", Name: "Timor-Leste [ab]"},
	{Code2: "TG", Code3: "TGO", Name: "Togo"},
	{Code2: "TK", Code3: "TKL", Name: "Tokelau"},
	{Code2: "TO", Code3: "TON", Name: "Tonga"},
	{Code2: "TT", Code3: "TTO", Name: "Trinidad and Tobago"},
	{Code2: "TN", Code3: "TUN", Name: "Tunisia"},
	{Code2: "TR", Code3: "TUR", Name: "Türkiye"},
	{Code2: "TM", Code3: "TKM", Name: "Turkmenistan"},
	{Code2: "TC", Code3: "TCA", Name: "Turks and Caicos Islands"},
	{Code2: "TV", Code3: "TUV", Name: "Tuvalu"},
	{Code2: "UG", Code3: "UGA", Name: "Uganda"},
	{Code2: "UA", Code3: "UKR", Name: "Ukraine"},
	{Code2: "AE", Code3: "ARE", Name: "United Arab Emirates"},
	{Code2: "GB", Code3: "GBR", Name: "United Kingdom of Great Britain and Northern Ireland"},
	{Code2: "UM", Code3: "UMI", Name: "United States Minor Outlying Islands"},
	{Code2: "US", Code3: "USA", Name: "United States of America"},
	{Code2: "UY", Code3: "URY", Name: "Uruguay"},
	{Code2: "UZ", Code3: "UZB", Name: "Uzbekistan"},
	{Code2: "VU", Code3: "VUT", Name: "Vanuatu"},
	{Code2: "VE", Code3: "VEN", Name: "Venezuela (Bolivarian Republic of)"},
	{Code2: "VN", Code3: "VNM", Name: "Viet Nam [ag]"},
	{Code2: "VG", Code3: "VGB", Name: "Virgin Islands (British)"},
	{Code2: "VI", Code3: "VIR", Name: "Virgin Islands (U.S.)"},
	{Code2: "WF", Code3: "WLF", Name: "Wallis and Futuna"},
	{Code2: "EH", Code3: "ESH", Name: "Western Sahara"},
	{Code2: "YE", Code3: "YEM", Name: "Yemen"},
	{Code2: "ZM", Code3: "ZMB", Name: "Zambia"},
	{Code2: "ZW", Code3: "ZWE", Name: "Zimbabwe"},
}
